Repository andela/jubilee-backend, pull requests merged in 2019-09, with the labels that each got.

#36 #168243791 Integrate User Roles to Signup features with permissions
  src/controllers/authController.js
  src/middlewares/authMiddleware.js
  src/middlewares/roleMiddleware.js
  src/routes/auth.js
  src/routes/users.js
  src/services/companyService.js
  src/services/roleService.js
  src/services/supplierService.js
  src/test/auth.spec.js
  src/test/dummies.js
  src/test/user.spec.js
  src/utils/helpers.js
  src/utils/index.js
  src/utils/permissions.js
  src/validation/authValidation.js
Labels: Ready for merge

#38 #167733674 Supplier admin can create an accommodation facility
  package.json
  src/controllers/authController.js
  src/controllers/facilityController.js
  src/controllers/index.js
  src/middlewares/authMiddleware.js
  src/middlewares/facilityMiddleware.js
  src/middlewares/index.js
  src/middlewares/roleMiddleware.js
  src/migrations/20190905134421-create-facility.js
  src/migrations/20190905134538-create-room.js
  src/migrations/20190905134648-create-amenity-facility.js
  src/migrations/20190905134742-create-room-category.js
  src/migrations/20190905134911-create-amenity.js
  src/models/amenity.js
  src/models/amenityfacility.js
  src/models/facility.js
  src/models/room.js
  src/models/roomcategory.js
  src/models/supplier.js
  src/routes/facility.js
  src/routes/index.js
  src/routes/users.js
  src/seeders/20190829110546-category-of-services.js
  src/seeders/20190906030545-amenities.js
  src/seeders/20190906040638-room-categories.js
  src/services/facilityService.js
  src/services/index.js
  src/services/roleService.js
  src/services/supplierService.js
  src/test/auth.test.js
  src/test/dummies.js
  src/test/facility.test.js
  src/test/user.test.js
  src/utils/factory.js
  src/utils/helpers.js
  src/utils/index.js
  src/utils/permissions.js
  src/utils/validationData.js
  src/validation/facilityValidator.js
  src/validation/index.js
  swagger.json
Labels: ready to merge

#37 #167733669 Implement Travel Admin Facility Creation
  package-lock.json
  package.json
  src/controllers/authController.js
  src/controllers/facilityController.js
  src/index.js
  src/middlewares/authMiddleware.js
  src/middlewares/facilityMiddleware.js
  src/middlewares/roleMiddleware.js
  src/migrations/20190905134421-create-facility.js
  src/migrations/20190905134538-create-room-category.js
  src/migrations/20190905134648-create-amenity.js
  src/migrations/20190905134742-create-room.js
  src/migrations/20190905134911-create-amenity-facility.js
  src/models/amenityfacility.js
  src/models/company.js
  src/models/facility.js
  src/models/room.js
  src/models/roomcategory.js
  src/routes/facility.js
  src/seeders/20190905132730-room-categories-seed.js
  src/seeders/20190906012830-amenities-seed.js
  src/services/companyService.js
  src/services/facilityService.js
  src/test/auth.test.js
  src/test/dummies.js
  src/test/facility.test.js
  src/utils/helpers.js
  src/utils/permissions.js
  src/utils/validationData.js
  src/validation/facilityValidator.js
  swagger.json
Labels: ttl review

#35 #167733675 Accommodation Booking
  package-lock.json
  package.json
  src/controllers/bookingController.js
  src/controllers/index.js
  src/middlewares/bookingMiddleware.js
  src/middlewares/index.js
  src/migrations/20190904171247-create-accommodation-booking.js
  src/migrations/20190905162555-add-booking-association.js
  src/models/accommodationbooking.js
  src/routes/booking.js
  src/routes/index.js
  src/services/bookingService.js
  src/services/index.js
  src/services/roomService.js
  src/test/booking.test.js
  src/validation/bookingValidator.js
  src/validation/index.js
  swagger.json
Labels: ready to merge

#41 #167733656 Integration of the requests table with the database
  src/controllers/index.js
  src/controllers/requestController.js
  src/middlewares/authMiddleware.js
  src/migrations/20190905143316-create-status.js
  src/migrations/20190905144601-create-request.js
  src/models/User.js
  src/models/accommodationbooking.js
  src/models/request.js
  src/models/status.js
  src/routes/users.js
  src/seeders/20190905172355-request-status-seeds.js
  src/services/index.js
  src/services/requestService.js
  src/test/dummies.js
  src/test/request.test.js
  src/test/user.test.js
  src/utils/permissions.js
  swagger.json
Labels: ttl review

#39 #167733651 Users should be able to make one-way trip request
  package-lock.json
  src/controllers/requestController.js
  src/database/migrations/20190905143316-create-status.js
  src/database/migrations/20190905144601-create-request.js
  src/database/migrations/20190912161129-create-add-passport-no-to-users-table.js
  src/database/seeders/20190905172355-request-status-seeds.js
  src/middlewares/index.js
  src/middlewares/tripRequestMiddleware.js
  src/models/User.js
  src/routes/index.js
  src/routes/trip.js
  src/services/index.js
  src/services/requestService.js
  src/test/dummies.js
  src/test/request.test.js
  src/validation/index.js
  src/validation/tripRequestValidation.js
  swagger.json
Labels: ttl review

#47 #167733660 Implement functionality for adding comments on Travel requests
  src/controllers/commentController.js
  src/controllers/facilityController.js
  src/controllers/index.js
  src/database/migrations/20190912135700-create-comment.js
  src/middlewares/commentMiddleware.js
  src/middlewares/index.js
  src/models/User.js
  src/models/comment.js
  src/models/request.js
  src/routes/comment.js
  src/routes/index.js
  src/services/commentService.js
  src/services/index.js
  src/services/requestService.js
  src/test/auth.test.js
  src/test/comment.test.js
  src/test/dummies.js
  src/test/request.test.js
  src/validation/index.js
  src/validation/otherValidators.js
  swagger.json
Labels: ttl review

#43 #168411451 Implement in-app notification module while using socket.io for real-time updates
  .eslintrc.json
  package-lock.json
  package.json
  src/controllers/authController.js
  src/controllers/index.js
  src/controllers/mockController.js
  src/database/migrations/20190910193740-create-notification.js
  src/database/migrations/20190912163935-remove-role-column-from-users-table.js
  src/index.js
  src/models/User.js
  src/models/notification.js
  src/models/supplier.js
  src/routes/index.js
  src/routes/mock.js
  src/services/index.js
  src/services/notificationService.js
  src/test/dummies.js
  src/test/notification.test.js
  src/test/request.test.js
  src/test/socketIO.test.js
  src/utils/index.js
  src/utils/notification.js
  src/utils/socketIO.js
  swagger.json
Labels: ttl review

#49 #167733663 Enable User to delete Comments made a on Travel Request
  src/controllers/commentController.js
  src/database/migrations/20190915234032-alter-request-managerId-non-null-constraint.js
  src/index.js
  src/middlewares/commentMiddleware.js
  src/routes/comment.js
  src/services/commentService.js
  src/test/comment.test.js
  src/test/request.test.js
  src/validation/tripRequestValidation.js
  swagger.json
Labels: ttl review

#48 #167733665 Mark notifications as read
  .eslintrc.json
  src/controllers/index.js
  src/controllers/notificationController.js
  src/routes/index.js
  src/routes/notification.js
  src/services/notificationService.js
  src/test/notification.test.js
  src/utils/helpers.js
  swagger.json
Labels: ttl review
